//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCommand
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public Groups()
        {
            this.People = new HashSet<Person>();
            this.Timeslot = new HashSet<Timeslots>();
        }
    
        public int GroupId { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Timeslots> Timeslot { get; set; }
    }
}
