//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCommand
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Person> People { get; set; }
        public DbSet<Timeslots> Timeslots { get; set; }
        public DbSet<Groups> Groups { get; set; }
        public DbSet<Rooms> Rooms { get; set; }
        public DbSet<Specialities> Specialities { get; set; }
        public DbSet<HasSpecialty> HasSpecialties { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<HasRole> HasRoles { get; set; }
        public DbSet<HasGroup> HasGroups { get; set; }
        public DbSet<GroupHasTimeslot> GroupHasTimeslots { get; set; }
    }
}
