//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCommand
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Group = new HashSet<Groups>();
        }
    
        public int PersonId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Age { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Groups> Group { get; set; }
        public virtual Students Student { get; set; }
        public virtual Teachers Teachers { get; set; }
        public virtual CaseManagers CaseManagers { get; set; }
    }
}
