//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCommand
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public Rooms()
        {
            this.Timeslots = new HashSet<Timeslots>();
        }
    
        public int RoomId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<Timeslots> Timeslots { get; set; }
    }
}
