//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCommand
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timeslots
    {
        public Timeslots()
        {
            this.Room = new HashSet<Rooms>();
        }
    
        public int TimeslotId { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual ICollection<Rooms> Room { get; set; }
    }
}
